---
spring:
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    driverClassName: org.h2.Driver
#    url: jdbc:mysql://localhost/pong_matcher_spring_development
    url: jdbc:h2:mem:pong_matcher_spring_development
    username: springpong
    password: springpong
  jpa:
    hibernate.ddl-auto: create-drop
    show_sql: true
